Python3 fixes: Use connection.write('foo'.encode())
PySerial running under Python 3 requires a bytestring be passed
to .write.
Curently, calls like connection.write('foo') are being used

This was the error:
$ sudo python3 cantact.py /dev/ttyACM0
Traceback (most recent call last):
  File "cantact.py", line 8, in <module>
    dev.start()
  File "/usr/lib/python3.4/site-packages/canard/hw/cantact.py", line 11, in start
    self.ser.write('O\r')
  File "/usr/lib/python3.4/site-packages/serial/serialposix.py", line 491, in write
    d = to_bytes(data)
  File "/usr/lib/python3.4/site-packages/serial/serialutil.py", line 76, in to_bytes
    b.append(item)  # this one handles int and str for our emulation and ints for Python 3.x
TypeError: an integer is required